

const degrees=[
  "Bachelor of Electrical Engineering",
  "BS Information Technology",
  "BBA Bachelor of Business Administration",
  "BS Islamic Sciences (BSIS)",
  "BS Dietetics & Nutritional Science",
  "Bachelor of Interior Design",
  "BS Nursing",
  "Doctor of Pharmacy",
  "Doctor of Physical Therapy (DPT)",
  "BS Software Engineering",
  "BSc Computer Science",
  "BS Mass Communication",
  "BCom",
  "BA",
  "BEd Arabic",
  "BEd Arts",
  "BS Chemistry",
  "Bachelor in Mass Communication",
  "BBA Bachelor of Business Administration",
  "Bachelor of Library & Information Science",
  "BA General Education",
  "BBA in Business Administration",
  "B.Com",
  "B.Ed. Education",
  "BSc General Education",
  "BS English",
  "BS IT",
  "BS Economic",
  "BS Mathematics",
  "BS Islamic Studies",
  "LLB (Hons)",
  "BS Management",
  "BS Computer Science",
  "BSc Electrical Engineering",
  "B.Com (Hons)",
  "BA English Literature (Hons.)",
  "BA History (Hons.)",
  "BA Islamic Studies (Hons.)",
  "BA Persian (Hons.)",
  "BA Philosophy",
  "BS Electrical Engineering Technology",
  "BSc Computer Systems Engineering",
  "BSc Electronic Engineering",
  "BS GENERAL HISTORY",
  "BS Library & Information Science",
  "BS Political Science",
  "Bachelor in Fine Arts & Design (Painting)",
  "BS Applied Psychology",
  "BS Secondary Education",
  "BS Social Work",
  "Associate Degree in Law",
  "Associate Degree Computer Science",
  "Associate Degree Business Administration",
  "Associate Degree Information Technology Commerce",
  "Associate Degree Software Technologies",
  "BTech Civil Technology",
  "BTech Electrical Technology",
  "Bachelor in Remote Sensing & Geographic Information System",
  "BS Computer Science (BSCS)",
  "BEd Anthropology",
  "BEd Communication Studies",
  "BEd Criminology",
  "BEd Education",
  "BEd Education Planning & Management",
  "BEd Geography",
  "BEd International Relations",
  "BEd Islamic Studies",
  "BEd LLB",
  "BEd Library Science",
  "BS English Literature",
  "BS Mathematics",
  "BS Economics",
  "BS Mass Communication",
  "BS Education",
  "BFA Craft and Textile Design",
  "BBA Bachelor of Business Administration",
  "BS Biotechnology",
  "BS Botany",
  "BS Chemistry",
  "BBA Hons",
  "BEd Elementary",
  "BEd Hons",
  "BEd Secondary",
  "BEd Special Education",
  "BFA",
  "BS Hons Botany",
  "BS Hons Chemistry",
  "BS Hons Economics",
  "BS Hons English",
  "BBS",
  "LLB",
  "BS Politics and International Relations",
  "BS Economics",
  "BS Management Sciences",
  "BS Chemistry",
  "BS Computer Science (BSCS)",
  "BS Earth Sciences",
  "BS Electronics",
  "BS Mathematics",
  "BSc Agronomy",
  "BSc Soil Science",
  "BSc Plant Breeding",
  "BSc Genetics",
  "BSc Horticulture",
  "BSc Plant Pathology",
  "BSc Entomology",
  "BSc Forestry",
  "BSc Range Management",
  'BSc Biotechnology',
  'ADP Computer Science',
  'ADP IT Management',
  'ADP zoology',
  'ADP Botany',
  'ADP Chemistry',
  'ADP Maths',
  'ADP Physics',
  'ADP Medical Lab Technology',
  'ADP Radio Imaging Technology',
  'ADP Surgical Lab Assistant',
  'BS Business Administration (BBA)',
  'BS Civil Engineering',
  'BS Electrical Engineering',
  'BS Mechanical Engineering',
  'BS Computer Science',
  'BS Software Engineering',
  'BS Mathematics',
  'BS Accounting & Finance',
  'BS Bioinformatics',
  'BS Food Science and Nutrition',
  'BBA Bachelor of Business Administration',
  'Bachelor of Dental Sciences (BDS)',
  'MBBS',
  'Bachelor of Medical Technology',
  'Doctor of Pharmacy (Pharm-D)',
  'BS Occupational Therapy',
  'BS Prosthetics & Orthotics',
  'Doctor of Physiotherapy (DPT)',
  'BS Nutrition',
  'Associate Degree in Bio Medical Engineering',
  'Other'
];
