

Map degree_subject_map = {
    "Bachelor of Electrical Engineering": ["Circuit Analysis", "Digital Electronics", "Electromagnetics", "Power Systems"],
    "BS Information Technology": ["Programming Fundamentals", "Database Management", "Network Security", "Web Development"],
    "BBA Bachelor of Business Administration": ["Marketing Management", "Financial Accounting", "Organizational Behavior", "Strategic Management"],
    "BS Islamic Sciences (BSIS)": ["Islamic History", "Quranic Studies", "Arabic Literature", "Islamic Jurisprudence"],
    "BS Dietetics & Nutritional Science": ["Nutrition Science", "Dietary Planning", "Biochemistry", "Food Microbiology"],
    "Bachelor of Interior Design": ["Design Principles", "Architectural Drafting", "Color Theory", "Furniture Design"],
    "BS Nursing": ["Anatomy and Physiology", "Patient Care", "Medical Surgical Nursing", "Community Health Nursing"],
    "Doctor of Pharmacy": ["Pharmacology", "Pharmaceutical Chemistry", "Pharmacotherapy", "Clinical Pharmacy"],
    "Doctor of Physical Therapy (DPT)": ["Musculoskeletal Physical Therapy", "Neurological Physical Therapy", "Cardiopulmonary Physical Therapy"],
    "BS Software Engineering": ["Software Design", "Algorithm Analysis", "Software Testing", "Object-Oriented Programming"],
    "BSc Computer Science": ["Data Structures", "Computer Networks", "Operating Systems", "Artificial Intelligence"],
    "BS Mass Communication": ["Media Studies", "Journalism", "Public Relations", "Broadcasting"],
    "BCom": ["Financial Accounting", "Managerial Accounting", "Business Economics", "Business Law"],
    "BA": ["Literature", "History", "Philosophy", "Social Sciences"],
    "BEd Arabic": ["Arabic Language Teaching Methods", "Arabic Literature", "Language Acquisition", "Cultural Studies"],
    "BEd Arts": ["Art Education", "Art History", "Visual Arts", "Educational Psychology"],
    "BS Chemistry": ["Inorganic Chemistry", "Organic Chemistry", "Physical Chemistry", "Analytical Chemistry"],
    "Bachelor in Mass Communication": ["Media and Society", "Digital Media Production", "Media Ethics", "Communication Theory"],
    "Bachelor of Library & Information Science": ["Information Organization", "Library Management", "Reference Services", "Digital Libraries"],
    "BA General Education": ["General Education Courses", "Humanities", "Social Sciences", "Natural Sciences"],
    "BBA in Business Administration": ["Business Ethics", "Operations Management", "International Business", "Entrepreneurship"],
    "B.Com": ["Financial Accounting", "Cost Accounting", "Business Statistics", "Taxation"],
    "B.Ed. Education": ["Educational Psychology", "Curriculum Development", "Classroom Management", "Assessment and Evaluation"],
    "BSc General Education": ["General Education Courses", "Science Foundation Courses", "Mathematics", "Social Sciences"],
    "BS English": ["English Literature", "Creative Writing", "Linguistics", "Critical Thinking"],
    "BS IT": ["Information Systems", "Database Management", "Web Development", "IT Project Management"],
    "BS Economics": ["Microeconomics", "Macroeconomics", "International Economics", "Econometrics"],
    "BS Mathematics": ["Calculus", "Linear Algebra", "Probability and Statistics", "Number Theory"],
    "BS Islamic Studies": ["Islamic Ethics", "Islamic History", "Comparative Religion", "Islamic Jurisprudence"],
    "LLB (Hons)": ["Constitutional Law", "Criminal Law", "Contract Law", "Legal Research and Writing"],
    "BS Management": ["Organizational Behavior", "Strategic Management", "Human Resource Management", "Business Ethics"],
    "BS Computer Science": ["Data Structures", "Algorithm Design", "Operating Systems", "Computer Networks"],
    "BSc Electrical Engineering": ["Circuit Analysis", "Electronics", "Digital Signal Processing", "Power Systems"],
    "B.Com (Hons)": ["Financial Accounting", "Business Law", "Managerial Economics", "Financial Management"],
    "BA English Literature (Hons.)": ["British Literature", "American Literature", "Shakespeare Studies", "Literary Theory"],
    "BA History (Hons.)": ["World History", "European History", "History of Science", "Historical Methods"],
    "BA Islamic Studies (Hons.)": ["Islamic Philosophy", "Islamic Ethics", "Comparative Religion", "Islamic History"],
    "BA Persian (Hons.)": ["Persian Literature", "Persian Grammar", "Persian History", "Persian Culture"],
    "BA Philosophy": ["Ethics", "Metaphysics", "Epistemology", "Philosophy of Mind"],
    "BS Electrical Engineering Technology": ["Electronics Technology", "Digital Systems", "Power Electronics", "Control Systems"],
    "BSc Computer Systems Engineering": ["Digital Logic Design", "Microprocessor Systems", "Computer Networks", "Embedded Systems"],
    "BSc Electronic Engineering": ["Analog Electronics", "Digital Signal Processing", "Communication Systems", "VLSI Design"],
    "BS GENERAL HISTORY": ["World History", "Historiography", "History of Science", "Globalization"],
    "BS Library & Information Science": ["Information Retrieval", "Cataloging and Classification", "Library Management", "Digital Libraries"],
    "BS Political Science": ["Political Theory", "International Relations", "Comparative Politics", "Public Policy"],
    "Bachelor in Fine Arts & Design (Painting)": ["Art History", "Painting Techniques", "Color Theory", "Visual Arts"],
    "BS Applied Psychology": ["General Psychology", "Clinical Psychology", "Counseling Psychology", "Psychological Research Methods"],
    "BS Secondary Education": ["Educational Psychology", "Teaching Methods", "Curriculum Development", "Assessment and Evaluation"],
    "BS Social Work": ["Social Welfare Policy", "Community Organizing", "Social Work Practice", "Human Behavior in the Social Environment"],
    "Associate Degree in Law": ["Introduction to Law", "Legal Research and Writing", "Civil Procedure", "Criminal Law"],
    "Associate Degree Computer Science": ["Programming Fundamentals", "Database Management", "Computer Networks", "Software Development"],
    "Associate Degree Business Administration": ["Introduction to Business", "Business Communication", "Financial Accounting", "Marketing"],
    "Associate Degree Information Technology Commerce": ["IT Fundamentals", "E-commerce", "Business Intelligence", "Information Systems"],
    "Associate Degree Software Technologies": ["Software Development", "Database Design", "Web Development", "Mobile App Development"],
    "BTech Civil Technology": ["Construction Management", "Structural Engineering", "Geotechnical Engineering", "Surveying"],
    "BTech Electrical Technology": ["Electrical Circuits", "Power Systems", "Digital Electronics", "Control Systems"],
    "Bachelor in Remote Sensing & Geographic Information System": ["Remote Sensing", "GIS Mapping",],
};

const degrees=[
  "Bachelor of Electrical Engineering",
  "BS Information Technology",
  "BBA Bachelor of Business Administration",
  "BS Islamic Sciences (BSIS)",
  "BS Dietetics & Nutritional Science",
  "Bachelor of Interior Design",
  "BS Nursing",
  "Doctor of Pharmacy",
  "Doctor of Physical Therapy (DPT)",
  "BS Software Engineering",
  "BSc Computer Science",
  "BS Mass Communication",
  "BCom",
  "BA",
  "BEd Arabic",
  "BEd Arts",
  "BS Chemistry",
  "Bachelor in Mass Communication",
  "BBA Bachelor of Business Administration",
  "Bachelor of Library & Information Science",
  "BA General Education",
  "BBA in Business Administration",
  "B.Com",
  "B.Ed. Education",
  "BSc General Education",
  "BS English",
  "BS IT",
  "BS Economic",
  "BS Mathematics",
  "BS Islamic Studies",
  "LLB (Hons)",
  "BS Management",
  "BS Computer Science",
  "BSc Electrical Engineering",
  "B.Com (Hons)",
  "BA English Literature (Hons.)",
  "BA History (Hons.)",
  "BA Islamic Studies (Hons.)",
  "BA Persian (Hons.)",
  "BA Philosophy",
  "BS Electrical Engineering Technology",
  "BSc Computer Systems Engineering",
  "BSc Electronic Engineering",
  "BS GENERAL HISTORY",
  "BS Library & Information Science",
  "BS Political Science",
  "Bachelor in Fine Arts & Design (Painting)",
  "BS Applied Psychology",
  "BS Secondary Education",
  "BS Social Work",
  "Associate Degree in Law",
  "Associate Degree Computer Science",
  "Associate Degree Business Administration",
  "Associate Degree Information Technology Commerce",
  "Associate Degree Software Technologies",
  "BTech Civil Technology",
  "BTech Electrical Technology",
  "Bachelor in Remote Sensing & Geographic Information System",
  "BS Computer Science (BSCS)",
  "BEd Anthropology",
  "BEd Communication Studies",
  "BEd Criminology",
  "BEd Education",
  "BEd Education Planning & Management",
  "BEd Geography",
  "BEd International Relations",
  "BEd Islamic Studies",
  "BEd LLB",
  "BEd Library Science",
  "BS English Literature",
  "BS Mathematics",
  "BS Economics",
  "BS Mass Communication",
  "BS Education",
  "BFA Craft and Textile Design",
  "BBA Bachelor of Business Administration",
  "BS Biotechnology",
  "BS Botany",
  "BS Chemistry",
  "BBA Hons",
  "BEd Elementary",
  "BEd Hons",
  "BEd Secondary",
  "BEd Special Education",
  "BFA",
  "BS Hons Botany",
  "BS Hons Chemistry",
  "BS Hons Economics",
  "BS Hons English",
  "BBS",
  "LLB",
  "BS Politics and International Relations",
  "BS Economics",
  "BS Management Sciences",
  "BS Chemistry",
  "BS Computer Science (BSCS)",
  "BS Earth Sciences",
  "BS Electronics",
  "BS Mathematics",
  "BSc Agronomy",
  "BSc Soil Science",
  "BSc Plant Breeding",
  "BSc Genetics",
  "BSc Horticulture",
  "BSc Plant Pathology",
  "BSc Entomology",
  "BSc Forestry",
  "BSc Range Management",
  'BSc Biotechnology',
  'ADP Computer Science',
  'ADP IT Management',
  'ADP zoology',
  'ADP Botany',
  'ADP Chemistry',
  'ADP Maths',
  'ADP Physics',
  'ADP Medical Lab Technology',
  'ADP Radio Imaging Technology',
  'ADP Surgical Lab Assistant',
  'BS Business Administration (BBA)',
  'BS Civil Engineering',
  'BS Electrical Engineering',
  'BS Mechanical Engineering',
  'BS Computer Science',
  'BS Software Engineering',
  'BS Mathematics',
  'BS Accounting & Finance',
  'BS Bioinformatics',
  'BS Food Science and Nutrition',
  'BBA Bachelor of Business Administration',
  'Bachelor of Dental Sciences (BDS)',
  'MBBS',
  'Bachelor of Medical Technology',
  'Doctor of Pharmacy (Pharm-D)',
  'BS Occupational Therapy',
  'BS Prosthetics & Orthotics',
  'Doctor of Physiotherapy (DPT)',
  'BS Nutrition',
  'Associate Degree in Bio Medical Engineering',
  'Other'
];
