// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_bmUqq0lj-qZtG3tFqGljcQfPLtmJLao',
    appId: '1:235621240563:web:ecfc26598e8e40b637b186',
    messagingSenderId: '235621240563',
    projectId: 'tutorus-75d11',
    authDomain: 'tutorus-75d11.firebaseapp.com',
    storageBucket: 'tutorus-75d11.appspot.com',
    measurementId: 'G-MVPJEMCG3D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT85vUETcwef70re42U3Br0H9RtVeLr4s',
    appId: '1:235621240563:android:57bbe36b79ab52fc37b186',
    messagingSenderId: '235621240563',
    projectId: 'tutorus-75d11',
    storageBucket: 'tutorus-75d11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO-hyGBu7qQ2GsDQqm1to8pMK7IyHba4o',
    appId: '1:235621240563:ios:b157ac34a1e03cb137b186',
    messagingSenderId: '235621240563',
    projectId: 'tutorus-75d11',
    storageBucket: 'tutorus-75d11.appspot.com',
    iosClientId: '235621240563-slveflm64piq6hbn66tb1fa26apjujsc.apps.googleusercontent.com',
    iosBundleId: 'com.example.tutorApp',
  );
}
